spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_nlw_spacetime?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.2728d8b433cd7796
            clientSecret: a43848802b9d3f6afe67a7d9b1da243b889aa4e5

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
